name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish -c Release -o release --nologo

      - name: Fix base href for GitHub Pages
        run: |
          sed -i 's/<base href="\/" \/>/<base href="\/bateka.games\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
